apiVersion: apps/v1
kind: Deployment #kind of manifest (Deployment)
metadata:
  creationTimestamp: null
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer #modify database in localhost
        name: adminer
        ports:
          - containerPort: 8080
        resources: {}
status: {}
