apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }} 
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.service.port }} 
        env: 
          - name: {{ .Values.env.host }}
            valueFrom:
              configMapKeyRef: 
                name: {{ .Values.Manifest.ConfigMap }} 
                key: {{ .Values.env.host }}
          - name: {{ .Values.env.user }} 
            valueFrom:
              secretKeyRef: 
                name: {{ .Values.Manifest.Secret }} 
                key: {{ .Values.env.user }}
          - name: {{ .Values.env.pass }}
            valueFrom:
              secretKeyRef: 
                name: {{ .Values.Manifest.Secret }}
                key: {{ .Values.env.pass }}
          - name: {{ .Values.env.name }} 
            valueFrom:
              configMapKeyRef: 
                name: {{ .Values.Manifest.ConfigMap }}
                key: {{ .Values.env.name }}
        resources: {}
status: {}

